dubbo:
  application:
    name: demo-api
    owner: luoan
  protocol:
    name: dubbo
    port: -1
  registry:
    address: zookeeper://127.0.0.1:2181
  scan:
    basePackages: com.anla.rpc.hellodubbo.api
  consumer:
    timeout: 5000
    check: false
  module:
    default: false
